# .github/workflows/deploy.yml

# Nombre del flujo de trabajo que aparecerá en la pestaña "Actions" de tu repositorio.
name: Deploy OncoGuía Pro to GitHub Pages

# Define cuándo se ejecutará este flujo de trabajo.
on:
  # Se activa cada vez que haces un 'push' a la rama 'main'.
  push:
    branches:
      - main
  
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Actions.
  workflow_dispatch:

# Establece los permisos necesarios para que el flujo de trabajo pueda interactuar con tu repositorio.
permissions:
  contents: read
  pages: write
  id-token: write

# Define los trabajos que se ejecutarán. En este caso, solo uno: 'deploy'.
jobs:
  deploy:
    # Configura el entorno de despliegue para usar GitHub Pages.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # La URL del sitio desplegado.
    
    # Especifica el sistema operativo en el que se ejecutará el trabajo.
    runs-on: ubuntu-latest

    # Define la secuencia de pasos que componen el trabajo.
    steps:
      # 1. Descarga el código de tu repositorio al entorno de ejecución.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura el entorno para el despliegue en GitHub Pages.
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3. "Construye" el artefacto del sitio. Como es un sitio estático,
      #    simplemente preparamos todos los archivos de la raíz para ser subidos.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Sube el contenido de la raíz del repositorio.
          path: '.'

      # 4. Despliega el artefacto subido a GitHub Pages.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4